import { TaskDetailRow } from '../types/domain';

/**
 * Detailed Task Data with Complete Vehicle Information
 * This data represents tasks with all associated vehicle details for the table view
 */
export const taskDetailFixtures: TaskDetailRow[] = [
  {
    id: 't1',
    title: 'Ölwechsel',
    description: 'Motoröl und Filter wechseln - Vollsynthetisches 5W-30 Öl verwenden',
    taskType: 'oil_change',
    priority: 'medium',
    assignee: 'Anna Schmidt',
    status: 'pending',
    dueDate: '2024-05-11',
    createdAt: '2024-05-05',
    vehicleId: 'v1',
    vehicleName: 'BMW 3er',
    brand: 'BMW',
    model: '320d xDrive',
    licensePlate: 'B-MW-3210',
    vin: 'WBA8E9105LCK12345',
    mileage: 45000,
    firstRegistration: '2021-03-15',
    fuelType: 'diesel',
    price: 32900,
    estimatedCost: 350,
    notes: 'Kunde wünscht Mobil 1 Öl, Termin bereits vereinbart',
  },
  {
    id: 't2',
    title: 'Reifenwechsel',
    description: 'Winterreifen montieren - 225/45 R18',
    taskType: 'tire_change',
    priority: 'high',
    assignee: 'Max Müller',
    status: 'in_progress',
    dueDate: '2024-05-13',
    createdAt: '2024-05-06',
    vehicleId: 'v2',
    vehicleName: 'Audi A4 Avant',
    brand: 'Audi',
    model: 'A4 Avant 2.0 TDI',
    licensePlate: 'M-AU-4567',
    vin: 'WAUZZZ8V8KA123456',
    mileage: 68000,
    firstRegistration: '2020-06-10',
    fuelType: 'diesel',
    price: 28500,
    estimatedCost: 280,
    notes: 'Reifendrucksensor prüfen, Winterreifen bereits gelagert',
  },
  {
    id: 't3',
    title: 'HU/AU Inspektion',
    description: 'TÜV Hauptuntersuchung und Abgasuntersuchung',
    taskType: 'inspection',
    priority: 'urgent',
    assignee: 'Lena Weber',
    status: 'pending',
    dueDate: '2024-05-10',
    createdAt: '2024-05-04',
    vehicleId: 'v3',
    vehicleName: 'VW Golf VIII',
    brand: 'Volkswagen',
    model: 'Golf VIII 1.5 TSI',
    licensePlate: 'HH-VW-8901',
    vin: '3VWDB7AJ5DM123456',
    mileage: 28000,
    firstRegistration: '2022-01-20',
    fuelType: 'benzin',
    price: 24900,
    estimatedCost: 185,
    notes: 'DRINGEND! TÜV läuft in 3 Tagen ab, Kunde bereits informiert',
  },
  {
    id: 't4',
    title: 'Bremsen vorne',
    description: 'Bremsbeläge und Scheiben erneuern',
    taskType: 'brake_repair',
    priority: 'high',
    assignee: 'Max Müller',
    status: 'pending',
    dueDate: '2024-05-14',
    createdAt: '2024-05-07',
    vehicleId: 'v4',
    vehicleName: 'Mercedes C200',
    brand: 'Mercedes-Benz',
    model: 'C 200 T-Modell',
    licensePlate: 'S-MB-2345',
    vin: 'WDD2050821F123456',
    mileage: 52000,
    firstRegistration: '2021-08-05',
    fuelType: 'benzin',
    price: 36500,
    estimatedCost: 650,
    notes: 'Original Mercedes-Teile verwenden, Bremsflüssigkeit ebenfalls erneuern',
  },
  {
    id: 't5',
    title: 'Motordiagnose',
    description: 'Check Engine Lampe prüfen - Fehlerspeicher auslesen',
    taskType: 'engine_repair',
    priority: 'medium',
    assignee: 'Anna Schmidt',
    status: 'in_progress',
    dueDate: '2024-05-12',
    createdAt: '2024-05-08',
    vehicleId: 'v5',
    vehicleName: 'BMW X3',
    brand: 'BMW',
    model: 'X3 xDrive20d',
    licensePlate: 'B-BM-9876',
    vin: 'WBAWL73509P123456',
    mileage: 89000,
    firstRegistration: '2019-11-20',
    fuelType: 'diesel',
    price: 38900,
    estimatedCost: 450,
    notes: 'Lambdasonde wahrscheinlich defekt, Ersatzteil bereits bestellt',
  },
  {
    id: 't6',
    title: 'Klimaanlage Service',
    description: 'Klimaanlage befüllen und desinfizieren',
    taskType: 'ac_repair',
    priority: 'low',
    assignee: 'Lena Weber',
    status: 'done',
    dueDate: '2024-05-08',
    createdAt: '2024-05-01',
    vehicleId: 'v6',
    vehicleName: 'Audi Q5',
    brand: 'Audi',
    model: 'Q5 45 TFSI quattro',
    licensePlate: 'M-AU-1122',
    vin: 'WAUZZZ8R6KA123456',
    mileage: 35000,
    firstRegistration: '2022-03-15',
    fuelType: 'benzin',
    price: 52900,
    estimatedCost: 220,
    notes: 'Erledigt - Klimaanlage funktioniert einwandfrei, Kunde zufrieden',
  },
  {
    id: 't7',
    title: 'Batterie tauschen',
    description: 'Neue Starterbatterie einbauen - 95Ah AGM',
    taskType: 'battery',
    priority: 'medium',
    assignee: 'Max Müller',
    status: 'done',
    dueDate: '2024-05-09',
    createdAt: '2024-05-03',
    vehicleId: 'v7',
    vehicleName: 'VW Passat',
    brand: 'Volkswagen',
    model: 'Passat Variant 2.0 TDI',
    licensePlate: 'HH-VW-3344',
    vin: '3VWCB7AJ8JM123456',
    mileage: 125000,
    firstRegistration: '2018-05-10',
    fuelType: 'diesel',
    price: 19900,
    estimatedCost: 280,
    notes: 'Erledigt - Varta AGM Batterie verbaut, Ladetest durchgeführt',
  },
  {
    id: 't8',
    title: 'Lack polieren',
    description: 'Fahrzeug polieren und versiegeln - Premium Keramikversiegelung',
    taskType: 'paint',
    priority: 'low',
    status: 'pending',
    dueDate: '2024-05-15',
    createdAt: '2024-05-09',
    vehicleId: 'v8',
    vehicleName: 'Porsche 911',
    brand: 'Porsche',
    model: '911 Carrera S',
    licensePlate: 'S-PO-7890',
    vin: 'WP0ZZZ99ZLS123456',
    mileage: 18000,
    firstRegistration: '2023-01-10',
    fuelType: 'benzin',
    price: 142000,
    estimatedCost: 1200,
    notes: 'High-End Service, 3-Stufen-Politur + Keramikversiegelung für 2 Jahre',
  },
  {
    id: 't9',
    title: 'Zahnriemen wechseln',
    description: 'Zahnriemenwechsel inkl. Wasserpumpe',
    taskType: 'engine_repair',
    priority: 'urgent',
    assignee: 'Anna Schmidt',
    status: 'pending',
    dueDate: '2024-05-11',
    createdAt: '2024-05-05',
    vehicleId: 'v9',
    vehicleName: 'Skoda Octavia',
    brand: 'Skoda',
    model: 'Octavia Combi 2.0 TDI',
    licensePlate: 'K-SK-5566',
    vin: 'TMBJJ7NE5K6123456',
    mileage: 158000,
    firstRegistration: '2017-09-15',
    fuelType: 'diesel',
    price: 15900,
    estimatedCost: 950,
    notes: 'WICHTIG! Kilometergrenze erreicht, Zahnriemen muss dringend gewechselt werden',
  },
  {
    id: 't10',
    title: 'Getriebe Service',
    description: 'Getriebeöl wechseln und Getriebe spülen',
    taskType: 'transmission',
    priority: 'medium',
    assignee: 'Max Müller',
    status: 'pending',
    dueDate: '2024-05-16',
    createdAt: '2024-05-10',
    vehicleId: 'v10',
    vehicleName: 'Ford Mustang',
    brand: 'Ford',
    model: 'Mustang GT 5.0',
    licensePlate: 'F-FO-1234',
    vin: '1FA6P8CF5L5123456',
    mileage: 72000,
    firstRegistration: '2020-06-20',
    fuelType: 'benzin',
    price: 48900,
    estimatedCost: 520,
    notes: 'Automatikgetriebe - Original Motorcraft Öl verwenden',
  },
  {
    id: 't11',
    title: 'Auspuff reparieren',
    description: 'Endtopf schweißen - Loch im Auspuff',
    taskType: 'exhaust',
    priority: 'high',
    assignee: 'Lena Weber',
    status: 'in_progress',
    dueDate: '2024-05-12',
    createdAt: '2024-05-08',
    vehicleId: 'v3',
    vehicleName: 'VW Golf VIII',
    brand: 'Volkswagen',
    model: 'Golf VIII 1.5 TSI',
    licensePlate: 'HH-VW-8901',
    vin: '3VWDB7AJ5DM123456',
    mileage: 28000,
    firstRegistration: '2022-01-20',
    fuelType: 'benzin',
    price: 24900,
    estimatedCost: 380,
    notes: 'Rostschaden am Endtopf, ggf. komplett erneuern falls Schweißen nicht möglich',
  },
  {
    id: 't12',
    title: 'Stoßdämpfer hinten',
    description: 'Stoßdämpfer hinten wechseln - beide Seiten',
    taskType: 'suspension',
    priority: 'medium',
    assignee: 'Max Müller',
    status: 'pending',
    dueDate: '2024-05-17',
    createdAt: '2024-05-11',
    vehicleId: 'v7',
    vehicleName: 'VW Passat',
    brand: 'Volkswagen',
    model: 'Passat Variant 2.0 TDI',
    licensePlate: 'HH-VW-3344',
    vin: '3VWCB7AJ8JM123456',
    mileage: 125000,
    firstRegistration: '2018-05-10',
    fuelType: 'diesel',
    price: 19900,
    estimatedCost: 620,
    notes: 'Kunde bemängelt instabiles Fahrverhalten, Stoßdämpfer undicht',
  },
  {
    id: 't13',
    title: 'Innenreinigung Premium',
    description: 'Komplette Innenreinigung mit Lederpflege und Ozonbehandlung',
    taskType: 'cleaning',
    priority: 'low',
    assignee: 'Anna Schmidt',
    status: 'pending',
    dueDate: '2024-05-18',
    createdAt: '2024-05-12',
    vehicleId: 'v4',
    vehicleName: 'Mercedes C200',
    brand: 'Mercedes-Benz',
    model: 'C 200 T-Modell',
    licensePlate: 'S-MB-2345',
    vin: 'WDD2050821F123456',
    mileage: 52000,
    firstRegistration: '2021-08-05',
    fuelType: 'benzin',
    price: 36500,
    estimatedCost: 350,
    notes: 'Für Verkaufsvorbereitung - Fahrzeug soll in Top-Zustand präsentiert werden',
  },
  {
    id: 't14',
    title: 'Scheinwerfer einstellen',
    description: 'LED-Scheinwerfer einstellen und prüfen',
    taskType: 'lights',
    priority: 'low',
    assignee: 'Lena Weber',
    status: 'done',
    dueDate: '2024-05-07',
    createdAt: '2024-05-02',
    vehicleId: 'v1',
    vehicleName: 'BMW 3er',
    brand: 'BMW',
    model: '320d xDrive',
    licensePlate: 'B-MW-3210',
    vin: 'WBA8E9105LCK12345',
    mileage: 45000,
    firstRegistration: '2021-03-15',
    fuelType: 'diesel',
    price: 32900,
    estimatedCost: 85,
    notes: 'Erledigt - Scheinwerfer neu eingestellt, Leuchtweitenregulierung geprüft',
  },
  {
    id: 't15',
    title: 'Windschutzscheibe tauschen',
    description: 'Steinschlag in Windschutzscheibe - kompletter Austausch notwendig',
    taskType: 'glass_repair',
    priority: 'high',
    assignee: 'Max Müller',
    status: 'in_progress',
    dueDate: '2024-05-13',
    createdAt: '2024-05-09',
    vehicleId: 'v6',
    vehicleName: 'Audi Q5',
    brand: 'Audi',
    model: 'Q5 45 TFSI quattro',
    licensePlate: 'M-AU-1122',
    vin: 'WAUZZZ8R6KA123456',
    mileage: 35000,
    firstRegistration: '2022-03-15',
    fuelType: 'benzin',
    price: 52900,
    estimatedCost: 890,
    notes: 'Original Audi Scheibe mit Regensensor und Head-Up Display Beschichtung',
  },
];
