import { Vehicle, VehicleFeature } from '../types/domain';

/**
 * Mock Vehicle Data - Rich variety of 10 vehicles
 */
export const vehicleFixtures: Vehicle[] = [
  {
    id: 'v1',
    internalId: 'CAR3028260',
    plate: 'B-MW-3210',
    vin: 'WBA8E9105LCK12345',
    brand: 'BMW',
    model: '3er',
    variant: '320d xDrive',
    category: 'limousine',
    year: 2021,
    firstRegistration: '2021-03-15',
    mileageKm: 45000,
    fuelType: 'diesel',
    transmission: 'automatik',
    transmissionDetail: '8-Gang Steptronic',
    engine: '2.0 TwinPower Turbo',
    power: { kw: 140, ps: 190 },
    color: 'Alpinweiß Metallic',
    colorHex: '#FFFFFF',
    seats: 5,
    doors: 4,
    condition: 'gebraucht',
    price: 32900,
    priceNet: 27647,
    purchasePrice: 28000,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800'
    ],
    features: [
      'automatik',
      'navigationssystem',
      'led-scheinwerfer',
      'klimaautomatik',
      'sitzheizung',
      'lenkradheizung',
      'einparkhilfe',
      'rückfahrkamera',
      'tempomat',
      'spurhalteassistent',
      'totwinkel-assistent',
      'leichtmetallfelgen',
      'ledersitze',
      'head-up-display',
      'digitales-kombiinstrument',
      'keyless-entry',
      'apple-carplay',
      'android-auto',
      'bluetooth',
      'usb',
      'isofix',
      'start-stop-automatik'
    ] as VehicleFeature[],
    co2Emission: 138,
    consumption: {
      city: 6.2,
      highway: 4.8,
      combined: 5.3
    },
    description: 'Gepflegter BMW 3er mit Vollausstattung, Erstbesitz, Scheckheftgepflegt',
    location: 'Berlin',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2024-12-24T14:30:00Z'
  },
  {
    id: 'v2',
    internalId: 'CAR3028261',
    plate: 'M-AU-4567',
    vin: 'WAUZZZ8V8KA123456',
    brand: 'Audi',
    model: 'A4 Avant',
    variant: '2.0 TDI quattro',
    category: 'kombi',
    year: 2020,
    firstRegistration: '2020-06-10',
    mileageKm: 68000,
    fuelType: 'diesel',
    transmission: 'automatik',
    transmissionDetail: '7-Gang S tronic',
    engine: '2.0 TDI',
    power: { kw: 110, ps: 150 },
    color: 'Navarrablau Metallic',
    colorHex: '#1E3A5F',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 28500,
    priceNet: 23950,
    purchasePrice: 24500,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1614026480886-81f71d3a9c71?w=800'
    ],
    features: [
      'automatik',
      'navigationssystem',
      'led-scheinwerfer',
      'sitzheizung',
      'panoramadach',
      'spurhalteassistent',
      'einparkhilfe',
      'rückfahrkamera',
      'klimaautomatik',
      '2-zonen-klimaautomatik',
      'leichtmetallfelgen',
      'tempomat',
      'allradantrieb',
      'teilleder',
      'keyless-entry',
      'apple-carplay',
      'android-auto',
      'bluetooth',
      'usb',
      'isofix'
    ] as VehicleFeature[],
    description: 'Komfortabler Kombi mit quattro-Antrieb, ideal für Familien',
    location: 'München',
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2024-12-23T16:00:00Z',
    co2Emission: 128,
    consumption: { city: 5.2, highway: 4.1, combined: 4.5 }
  },
  {
    id: 'v3',
    internalId: 'CAR3028262',
    plate: 'HH-VW-8901',
    vin: '3VWDB7AJ5DM123456',
    brand: 'Volkswagen',
    model: 'Golf',
    variant: 'VIII 1.5 TSI',
    category: 'kleinwagen',
    year: 2022,
    firstRegistration: '2022-01-20',
    mileageKm: 28000,
    fuelType: 'benzin',
    transmission: 'manuell',
    transmissionDetail: '6-Gang Schaltgetriebe',
    engine: '1.5 TSI',
    power: { kw: 96, ps: 130 },
    color: 'Kings Red Metallic',
    colorHex: '#8B0000',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 24900,
    priceNet: 20924,
    purchasePrice: 21000,
    status: 'reserved',
    availability: 'Reserviert',
    images: [
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
      'https://images.unsplash.com/photo-1610884461619-7f4e2f3e8c3c?w=800'
    ],
    features: [
      'digitales-kombiinstrument',
      'apple-carplay',
      'android-auto',
      'rückfahrkamera',
      'tempomat',
      'bluetooth',
      'usb',
      'klimaanlage',
      'einparkhilfe',
      'led-scheinwerfer',
      'leichtmetallfelgen',
      'start-stop-automatik',
      'isofix',
      'regensensor',
      'lichtsensor'
    ] as VehicleFeature[],
    description: 'Neuwertig, wenig Kilometer, ideales Stadtauto',
    location: 'Hamburg',
    customerId: 'c1',
    createdAt: '2024-12-10T11:00:00Z',
    updatedAt: '2024-12-24T10:00:00Z',
    co2Emission: 122,
    consumption: { city: 6.1, highway: 4.3, combined: 4.9 }
  },
  {
    id: 'v4',
    internalId: 'CAR3028263',
    plate: 'S-MB-2345',
    vin: 'WDD2130421A123456',
    brand: 'Mercedes-Benz',
    model: 'C-Klasse',
    variant: 'C 220 d AMG Line',
    category: 'limousine',
    year: 2019,
    firstRegistration: '2019-09-05',
    mileageKm: 92000,
    fuelType: 'diesel',
    transmission: 'automatik',
    transmissionDetail: '9G-TRONIC',
    engine: '2.0 OM 654',
    power: { kw: 143, ps: 194 },
    color: 'Obsidianschwarz Metallic',
    colorHex: '#0C0C0C',
    seats: 5,
    doors: 4,
    condition: 'gebraucht',
    price: 29900,
    priceNet: 25126,
    purchasePrice: 26000,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800'
    ],
    features: [
      'automatik',
      'navigationssystem',
      'led-scheinwerfer',
      'sportpaket',
      'soundsystem',
      '360-grad-kamera',
      'sitzheizung',
      'ledersitze',
      'klimaautomatik',
      '2-zonen-klimaautomatik',
      'einparkhilfe',
      'rückfahrkamera',
      'tempomat',
      'adaptiver-tempomat',
      'spurhalteassistent',
      'totwinkel-assistent',
      'leichtmetallfelgen',
      'keyless-go',
      'apple-carplay',
      'android-auto',
      'bluetooth',
      'usb'
    ] as VehicleFeature[],
    description: 'Sportliches Design, gehobene Ausstattung, gepflegter Zustand',
    location: 'Stuttgart',
    createdAt: '2024-11-20T14:00:00Z',
    updatedAt: '2024-12-22T09:00:00Z',
    co2Emission: 135,
    consumption: { city: 5.8, highway: 4.2, combined: 4.8 }
  },
  {
    id: 'v5',
    internalId: 'CAR3028264',
    plate: 'K-OP-6789',
    vin: 'VF1RFE00557123456',
    brand: 'Renault',
    model: 'Zoe',
    variant: 'R135 Intens',
    category: 'kleinwagen',
    year: 2023,
    firstRegistration: '2023-04-12',
    mileageKm: 12000,
    fuelType: 'elektro',
    transmission: 'automatik',
    transmissionDetail: 'Automatik',
    engine: 'Elektromotor',
    power: { kw: 100, ps: 136 },
    color: 'Eisblau Metallic',
    colorHex: '#B0E0E6',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 26500,
    priceNet: 22269,
    purchasePrice: 23000,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
      'https://images.unsplash.com/photo-1617704548623-340376564e68?w=800'
    ],
    features: [
      'automatik',
      'navigationssystem',
      'klimaautomatik',
      'sitzheizung',
      'rückfahrkamera',
      'einparkhilfe',
      'tempomat',
      'led-scheinwerfer',
      'leichtmetallfelgen',
      'apple-carplay',
      'android-auto',
      'bluetooth',
      'usb',
      'isofix',
      'regensensor',
      'start-stop-automatik'
    ] as VehicleFeature[],
    description: 'Elektroauto mit großer Reichweite, umweltfreundlich und kostengünstig',
    location: 'Köln',
    createdAt: '2024-12-05T08:00:00Z',
    updatedAt: '2024-12-24T12:00:00Z',
    co2Emission: 0,
    consumption: { city: 0, highway: 0, combined: 0 }
  },
  {
    id: 'v6',
    internalId: 'CAR3028265',
    plate: 'F-PO-1122',
    vin: 'WP0ZZZ99ZTS123456',
    brand: 'Porsche',
    model: 'Cayenne',
    variant: 'S E-Hybrid',
    category: 'suv',
    year: 2021,
    firstRegistration: '2021-07-30',
    mileageKm: 38000,
    fuelType: 'plug-in-hybrid',
    transmission: 'automatik',
    transmissionDetail: '8-Gang Tiptronic S',
    engine: '3.0 V6 Turbo + E-Motor',
    power: { kw: 324, ps: 440 },
    color: 'Carraragrau Metallic',
    colorHex: '#A9A9A9',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 78900,
    priceNet: 66303,
    purchasePrice: 70000,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1611859266238-4b98091d9d9b?w=800',
      'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800'
    ],
    features: [
      'automatik',
      'allradantrieb',
      'luftfederung',
      'sportpaket',
      'panoramadach',
      'soundsystem',
      'ledersitze',
      'sitzheizung',
      'sitzbelueftung',
      'massagefunktion',
      'head-up-display',
      'navigationssystem',
      'led-scheinwerfer',
      'adaptiver-tempomat',
      'spurhalteassistent',
      '360-grad-kamera',
      'einparkhilfe',
      'keyless-go',
      'leichtmetallfelgen',
      'apple-carplay',
      'android-auto',
      'bluetooth'
    ] as VehicleFeature[],
    description: 'Luxus-SUV mit Hybrid-Antrieb, maximaler Komfort und Performance',
    location: 'Frankfurt',
    createdAt: '2024-11-25T15:00:00Z',
    updatedAt: '2024-12-23T11:00:00Z',
    co2Emission: 75,
    consumption: { city: 3.2, highway: 6.8, combined: 4.5 }
  },
  {
    id: 'v7',
    internalId: 'CAR3028266',
    plate: 'DD-TO-3344',
    vin: 'NMTKHMBXXMR123456',
    brand: 'Toyota',
    model: 'RAV4',
    variant: 'Hybrid Style',
    category: 'suv',
    year: 2022,
    firstRegistration: '2022-02-18',
    mileageKm: 35000,
    fuelType: 'hybrid',
    transmission: 'automatik',
    transmissionDetail: 'E-CVT Automatik',
    engine: '2.5 Hybrid',
    power: { kw: 130, ps: 177 },
    color: 'Silvermetallic',
    colorHex: '#C0C0C0',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 34500,
    priceNet: 28992,
    purchasePrice: 30000,
    status: 'sold',
    availability: 'Verkauft',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800'
    ],
    features: [
      'automatik',
      'allradantrieb',
      'sitzheizung',
      'einparkhilfe',
      'apple-carplay',
      'android-auto',
      'r\u00fcckfahrkamera',
      'tempomat',
      'adaptiver-tempomat',
      'spurhalteassistent',
      'totwinkel-assistent',
      'klimaautomatik',
      '2-zonen-klimaautomatik',
      'led-scheinwerfer',
      'leichtmetallfelgen',
      'bluetooth',
      'usb',
      'isofix'
    ] as VehicleFeature[],
    description: 'Zuverlässiger Hybrid-SUV mit geringem Verbrauch',
    location: 'Dresden',
    customerId: 'c2',
    createdAt: '2024-11-10T10:00:00Z',
    updatedAt: '2024-12-20T14:00:00Z',
    co2Emission: 102,
    consumption: { city: 4.8, highway: 4.3, combined: 4.5 }
  },
  {
    id: 'v8',
    internalId: 'CAR3028267',
    plate: 'L-FO-5566',
    vin: 'WF05XXGCB5KP12345',
    brand: 'Ford',
    model: 'Mustang Mach-E',
    variant: 'Extended Range AWD',
    category: 'suv',
    year: 2023,
    firstRegistration: '2023-05-22',
    mileageKm: 18000,
    fuelType: 'elektro',
    transmission: 'automatik',
    transmissionDetail: 'Automatik',
    engine: 'Dual Motor Elektromotor',
    power: { kw: 198, ps: 269 },
    color: 'Rapid Red Metallic',
    colorHex: '#DC143C',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 52900,
    priceNet: 44454,
    purchasePrice: 48000,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800',
      'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800'
    ],
    features: [
      'automatik',
      'allradantrieb',
      'luftfederung',
      'navigationssystem',
      'soundsystem',
      'panoramadach',
      'ledersitze',
      'sitzheizung',
      'sitzbelueftung',
      '360-grad-kamera',
      'einparkhilfe',
      'r\u00fcckfahrkamera',
      'adaptiver-tempomat',
      'spurhalteassistent',
      'totwinkel-assistent',
      'led-scheinwerfer',
      'head-up-display',
      'keyless-go',
      'apple-carplay',
      'android-auto',
      'bluetooth',
      'usb'
    ] as VehicleFeature[],
    description: 'Sportlicher Elektro-SUV mit beeindruckender Reichweite',
    location: 'Leipzig',
    createdAt: '2024-12-08T13:00:00Z',
    updatedAt: '2024-12-24T08:00:00Z',
    co2Emission: 0,
    consumption: { city: 0, highway: 0, combined: 0 }
  },
  {
    id: 'v9',
    internalId: 'CAR3028268',
    plate: 'N-SK-7788',
    vin: 'TMBEJ6NE0L7123456',
    brand: 'Skoda',
    model: 'Octavia Combi',
    variant: '2.0 TDI Style',
    category: 'kombi',
    year: 2020,
    firstRegistration: '2020-10-05',
    mileageKm: 78000,
    fuelType: 'diesel',
    transmission: 'manuell',
    transmissionDetail: '6-Gang Schaltgetriebe',
    engine: '2.0 TDI',
    power: { kw: 85, ps: 115 },
    color: 'Stahlgrau Metallic',
    colorHex: '#71797E',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 19900,
    priceNet: 16723,
    purchasePrice: 17000,
    status: 'service',
    availability: 'In Wartung',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800'
    ],
    features: [
      'navigationssystem',
      'tempomat',
      'klimaautomatik',
      'einparkhilfe',
      'r\u00fcckfahrkamera',
      'bluetooth',
      'usb',
      'isofix',
      'led-scheinwerfer',
      'leichtmetallfelgen',
      'regensensor',
      'lichtsensor',
      'start-stop-automatik'
    ] as VehicleFeature[],
    description: 'Praktischer Kombi mit viel Platz, zuverlässig und sparsam',
    location: 'Nürnberg',
    createdAt: '2024-11-18T12:00:00Z',
    updatedAt: '2024-12-21T10:00:00Z',
    co2Emission: 118,
    consumption: { city: 5.0, highway: 3.9, combined: 4.3 }
  },
  {
    id: 'v10',
    internalId: 'CAR3028269',
    plate: 'DU-OP-9900',
    vin: 'VF34ARFYF53123456',
    brand: 'Opel',
    model: 'Corsa',
    variant: '1.2 Turbo Edition',
    category: 'kleinwagen',
    year: 2023,
    firstRegistration: '2023-08-14',
    mileageKm: 8500,
    fuelType: 'benzin',
    transmission: 'manuell',
    transmissionDetail: '6-Gang Schaltgetriebe',
    engine: '1.2 Turbo',
    power: { kw: 74, ps: 100 },
    color: 'Voltaic Blue Metallic',
    colorHex: '#0047AB',
    seats: 5,
    doors: 5,
    condition: 'gebraucht',
    price: 18900,
    priceNet: 15882,
    purchasePrice: 16500,
    status: 'available',
    availability: 'Sofort verfügbar',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800'
    ],
    features: [
      'klimaanlage',
      'spurhalteassistent',
      'bluetooth',
      'usb',
      'tempomat',
      'einparkhilfe',
      'r\u00fcckfahrkamera',
      'apple-carplay',
      'android-auto',
      'led-scheinwerfer',
      'leichtmetallfelgen',
      'isofix',
      'start-stop-automatik',
      'regensensor',
      'lichtsensor'
    ] as VehicleFeature[],
    description: 'Kompakter Kleinwagen, ideal für die Stadt, modern und effizient',
    location: 'Duisburg',
    createdAt: '2024-12-12T09:00:00Z',
    updatedAt: '2024-12-24T07:00:00Z',
    co2Emission: 108,
    consumption: { city: 5.8, highway: 4.0, combined: 4.7 }
  }
];

// Helper functions for filtering and searching
export const getVehiclesByStatus = (status: Vehicle['status']) => {
  return vehicleFixtures.filter(v => v.status === status);
};

export const getAvailableVehicles = () => getVehiclesByStatus('available');
export const getReservedVehicles = () => getVehiclesByStatus('reserved');
export const getSoldVehicles = () => getVehiclesByStatus('sold');

export const searchVehicles = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return vehicleFixtures.filter(v => 
    v.brand.toLowerCase().includes(lowerQuery) ||
    v.model.toLowerCase().includes(lowerQuery) ||
    v.plate.toLowerCase().includes(lowerQuery) ||
    v.vin.toLowerCase().includes(lowerQuery)
  );
};
