import { VehicleFeature } from '../types/domain';
import {
  Settings2,
  Snowflake,
  Navigation,
  Lightbulb,
  CircleDot,
  Camera,
  Video,
  Link2,
  Sun,
  Gauge,
  Shield,
  Eye,
  Moon,
  CloudRain,
  AlertTriangle,
  Volume2,
  Smartphone,
  Usb,
  Baby,
  Wind,
  Key,
  Power,
  Mountain,
  Waves,
  Zap,
  Thermometer,
  Radio,
  Sofa,
  Car
} from 'lucide-react';

export const featureIconMap: Record<VehicleFeature, { icon: any; label: string }> = {
  'automatik': { icon: Settings2, label: 'Automatikgetriebe' },
  'klimaanlage': { icon: Snowflake, label: 'Klimaanlage' },
  'klimaautomatik': { icon: Snowflake, label: 'Klimaautomatik' },
  '2-zonen-klimaautomatik': { icon: Snowflake, label: '2-Zonen-Klimaautomatik' },
  'sitzheizung': { icon: Thermometer, label: 'Sitzheizung' },
  'lenkradheizung': { icon: Thermometer, label: 'Lenkradheizung' },
  'navigationssystem': { icon: Navigation, label: 'Navigationssystem' },
  'led-scheinwerfer': { icon: Lightbulb, label: 'LED-Scheinwerfer' },
  'xenon-scheinwerfer': { icon: Lightbulb, label: 'Xenon-Scheinwerfer' },
  'leichtmetallfelgen': { icon: CircleDot, label: 'Leichtmetallfelgen' },
  'einparkhilfe': { icon: Radio, label: 'Einparkhilfe' },
  'rückfahrkamera': { icon: Camera, label: 'Rückfahrkamera' },
  '360-grad-kamera': { icon: Video, label: '360-Grad-Kamera' },
  'anhängerkupplung': { icon: Link2, label: 'Anhängerkupplung' },
  'anhängerkupplung-abnehmbar': { icon: Link2, label: 'Anhängerkupplung abnehmbar' },
  'panoramadach': { icon: Sun, label: 'Panoramadach' },
  'schiebedach': { icon: Sun, label: 'Schiebedach' },
  'tempomat': { icon: Gauge, label: 'Tempomat' },
  'adaptiver-tempomat': { icon: Gauge, label: 'Adaptiver Tempomat' },
  'spurhalteassistent': { icon: Shield, label: 'Spurhalteassistent' },
  'totwinkel-assistent': { icon: Eye, label: 'Totwinkel-Assistent' },
  'fernlichtassistent': { icon: Moon, label: 'Fernlichtassistent' },
  'müdigkeitswarner': { icon: AlertTriangle, label: 'Müdigkeitswarner' },
  'notbremsassistent': { icon: Shield, label: 'Notbremsassistent' },
  'verkehrszeichenerkennung': { icon: Eye, label: 'Verkehrszeichenerkennung' },
  'einparkhilfe-selbsttätig': { icon: Radio, label: 'Einparkhilfe selbsttätig' },
  'head-up-display': { icon: Eye, label: 'Head-Up Display' },
  'digitales-kombiinstrument': { icon: Gauge, label: 'Volldigitales Kombiinstrument' },
  'ledersitze': { icon: Sofa, label: 'Ledersitze' },
  'teilleder': { icon: Sofa, label: 'Teilleder' },
  'sportpaket': { icon: Zap, label: 'Sportpaket' },
  'soundsystem': { icon: Volume2, label: 'Premium Soundsystem' },
  'freisprecheinrichtung': { icon: Smartphone, label: 'Freisprecheinrichtung' },
  'apple-carplay': { icon: Smartphone, label: 'Apple CarPlay' },
  'android-auto': { icon: Smartphone, label: 'Android Auto' },
  'bluetooth': { icon: Radio, label: 'Bluetooth' },
  'usb': { icon: Usb, label: 'USB-Anschluss' },
  'isofix': { icon: Baby, label: 'ISOFIX' },
  'beheizbare-frontscheibe': { icon: Wind, label: 'Beheizbare Frontscheibe' },
  'regensensor': { icon: CloudRain, label: 'Regensensor' },
  'lichtsensor': { icon: Lightbulb, label: 'Lichtsensor' },
  'keyless-entry': { icon: Key, label: 'Keyless Entry' },
  'keyless-go': { icon: Key, label: 'Keyless Go' },
  'start-stop-automatik': { icon: Power, label: 'Start-Stop-Automatik' },
  'allradantrieb': { icon: Mountain, label: 'Allradantrieb' },
  'luftfederung': { icon: Waves, label: 'Luftfederung' },
  'sportfahrwerk': { icon: Car, label: 'Sportfahrwerk' }
};
